AppLogin/urls.py
from django.urls import path
from  . import views

app_name= 'AppLogin'

urlpatterns = [
    path('signup/', views.sign_up,name='signup'),
    path('signin/', views.login_page,name='signin'),
    path('logout/', views.logout_user,name='logout'),
    path('profile/', views.profile,name='profile'),
    path('change_profile/', views.user_change,name='user_change'),
    path('password/', views.pass_change,name='pass_change'),
    path('change-profile-image/', views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic,name='change_pro_pic'),
       
]

Home/urls.py
from django.urls import path
from Home import views
app_name = 'Home'


urlpatterns =[
    path('',views.index,name='home'),
    path('personal',views.personal,name="personal"),
    path('productivity',views.productivity,name="productivity"),
    
]

balanced_me/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('Home.urls')),
    path('',views.index,name='index'),
    path('account/',include('AppLogin.urls')),
]

AppLogin/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User,related_name='user_profile',on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

Home/models.py
from django.db import models

# Create your models here.

AppLogin/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from django.forms import fields
from AppLogin.models import UserProfile

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label=" Email Address ",required=True)
    class Meta:
        model= User
        fields =('username','email','password1','password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model=User
        fields=('username', 'email','first_name','last_name','password')
        


class ProfilePic(forms.ModelForm):
    class Meta:
        model= UserProfile
        fields=['profile_pic',]

AppLogin/views.py
from AppLogin.forms import ProfilePic, SignUpForm, UserProfileChange
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm,PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from AppLogin.forms import SignUpForm,UserProfileChange,ProfilePic


# Create your views here.
def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method =='POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered=True
    dict = {'form':form,'registered':registered}

    return render(request,'AppLogin/signup.html',context=dict)



def login_page(request):
    form= AuthenticationForm()
    if request.method =='POST':
        form =AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

    return render(request, 'AppLogin/login.html', context={'form':form})



@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('AppLogin:signin'))




@login_required
def profile(request):
    return render(request, 'AppLogin/profile.html', context={})


@login_required   
def user_change(request):
    current_user = request.user
   
    form = UserProfileChange(instance=current_user)
    if request.method =='POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)  
    return render(request, 'AppLogin/change_profile.html', context={'form':form})



@login_required   
def pass_change(request):
    current_user= request.user
    changed = False
    form = PasswordChangeForm(current_user)

    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True

    return render(request,'AppLogin/pass_change.html',context={'form':form,'changed':changed})




@login_required   
def add_pro_pic(request):
    form = ProfilePic()
    if request.method =='POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit = False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('AppLogin:profile'))
    return render(request, 'AppLogin/pro_pic_add.html',context={'form':form})


@login_required  
def change_pro_pic(request):
    form =ProfilePic(instance= request.user.user_profile)
    if request.method=='POST':
        form = ProfilePic(request.POST, request.FILES, instance = request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('AppLogin:profile'))
    return render(request, 'AppLogin/pro_pic_add.html',context={'form':form})

Home/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView
from django.http import HttpResponse
# Create your views here.
def index(request):
    return render(request,'Home/home.html')

class home(ListView):
    template_name='Home/home.html'
def personal(request):
    return render(request,'Home/personal.html')
def productivity(request):
    return render(request,'Home/productivity.html')

balanced_me/views.py
from django.http import HttpResponse
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse

def index(request):
    return HttpResponseRedirect(reverse('Home:home'))

templates/AppLogin/change_profile.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}

{% block title %} Change User Profile {% endblock title %}


{% block body_block %}
<div class="userchangeprofile">
    <div class="userchangeprofilebox">
        <h2>User Profile Change</h2>
<form  method="post">
    {{form|crispy}}

    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Change</button>

</form>

    </div>

</div>

{% endblock body_block %}

templates/AppLogin/login.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}

{% block title %} Login Page {% endblock title %}


{% block body_block %}
<div class="mainbasecontainer">
    <div class="form">
        <h2>Login Your Account</h2>
    <form  method="post">
        {{form|crispy}}
    
        {% csrf_token %}
        <button type="submit" class="custom-btn btn-2">Login</button>
    
    </form>
    </div>
    
</div>

{% endblock body_block %}

templates/AppLogin/pass_change.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}

{% block title %} Password Change Page {% endblock title %}


{% block body_block %}

{% if changed %}

<div class="alert alert-success">

    Password Change Successfully

</div>

{% endif %}

<div class="passwordchangebox">
    
<h2>Password Change</h2>
<form  method="post">
    {{form|crispy}}

    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Change</button>

</form>

</div>

{% endblock body_block %}

templates/AppLogin/pro_pic_add.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}

{% block title %} Profile Pic Update {% endblock title %}


{% block body_block %}
<div class="addprofilepic">
    <h2>Add Your Profile Picture</h2>
    <div class="addprofilepicbox">
        <form  method="post" enctype="multipart/form-data">
            {{form|crispy}}
        
            {% csrf_token %}
            <button type="submit" class="custom-btn btn-2">Add Picture</button>
        
        </form>

    </div>


</div>


{% endblock body_block %}

templates/AppLogin/profile.html
{% extends 'Base.html' %}
{% load static %}
{% block title %} Profile Page {% endblock title %}


{% block body_block %}

    
<div class="profile-container">
<h2> Your Profile</h2>


<div class="profile-card">

{% if user.user_profile %}

<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="120px"  alt="">
<br>
<a href="{% url 'AppLogin:change_pro_pic'%} " class="btn btn-info btn-sm">Change Profile</a>

{% else %}
<img src="/media/download.jpg" class="rounded-circle"  width="120px" alt="">
<br>
<a href="{% url 'AppLogin:add_pro_pic'%}" class="btn btn-info btn-sm">Change Profile Pic</a>

{% endif %}
<p>Username :{{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Name :{{ user.first_name }} {{ user.last_name }}</p>

<br>
<a href="{% url 'AppLogin:user_change' %}" class="btn btn-warning btn-sm"> Change Profile Info</a>
{% endblock body_block %}
</div>
</div>

templates/AppLogin/signup.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}

{% block title %} Create New Account{% endblock title %}


{% block body_block %}

{% if registered %}
<div class="alert alert-success">
    Account created successfully <a href="{%  url 'AppLogin:signin' %}"> Login Here</a>
</div>
{% else %}
<div class="enter">
<h1>Create New Account</h1>
<form method="post">
    
   {{ form | crispy }} 
   {% csrf_token %}
   <button type="submit" style="width: 12rem;" class="custom-btn btn-2">Create Account</button>

</form>
<br>
<p>Already Have an account? <a href="{% url 'AppLogin:signin' %}"><button type="submit" class="custom-btn btn-2">Login Here</button></a></p>
{% endif %}
</div>
{% endblock %}

templates/Base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

     <link rel="stylesheet" href="{% static 'css/quiz.css' %}" >
    <link rel="stylesheet" href="{% static 'css/home.css' %}" >

    <title>Balanced_Me</title>
    
    <title>

        {% block title %}

          DecryptHer

        {% endblock %}

    </title>
</head>
<body>
    <section class="nav-bar">
        <div class="nav-container">
           
            <nav  >
                <div class="nav-left">
                     <span>
                    <!-- <img src={%static " " %} alt="logo"> -->
                    <span class="brand-logo">Balanced_Me</span>
                    </span>
                </div>
                <div class="nav-list nav-right">                    
                    <span>
                        <a href="{% url 'index' %}">Home</a>
                    </span>
                    {% if user.is_authenticated %}
                    
                    <span>
                        <a href="{% url 'Home:personal'%}">Personal Life</a>
                       
                    </span>
                    <span>
                        <a href="{% url 'Home:productivity'%}">Productivity</a>
                       
                    </span>
                    
                    
                    <span>
                        <a href="{% url 'AppLogin:profile' %}">{{ user.username }}</a>
                    </span>

                    <span>
                        <a href="{% url 'AppLogin:logout' %}">Logout</a>
                    </span>
                    {% else %}
                    <span>
                        <a href="{% url 'AppLogin:signup' %}">Sign Up</a>
                    </span>
                    <span>
                        <a href="{% url 'AppLogin:signin' %}">Login</a>
                    </span>
                    


                    {% endif %}


                </div>

            </nav>
        </div>
    </section>

    <div class="containermain">
    
     {% comment %} {% include "./Home/navbar.html" %} {% endcomment %}

        <div class="main pt-2">

            {% block body_block %}

            {% endblock %}

        </div>
    </div>
    <footer style="  
    margin-top: 2rem;
    height: 14rem;
    background: #a72c83;
    display: flex;
    justify-content: center;">
        <span style="font-size: 4rem;
        color: white;
    ">Balanced_Me</span>

    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

<script>
    (function ($) {
        $(function () {
            $('nav ul li a:not(:only-child)').click(function (e) {
                $(this).siblings('.nav-dropdown').toggle();
                $('.dropdown').not($(this).siblings()).hide();
                e.stopPropagation();
            });
            $('html').click(function () {
                $('.nav-dropdown').hide();
            });
            $('#nav-toggle').click(function () {
                $('nav ul').slideToggle();
            });
            $('#nav-toggle').on('click', function () {
                this.classList.toggle('active');
            });
        });
    })(jQuery);

</script>
</body>

    </html>
  

templates/Home/home.html
{% extends 'Base.html' %}


{% load static %}
{% block title %} Home {% endblock title %}

{% block body_block %}

{% comment %} <nav class="navbar navbar-expand-lg ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
    </div>
  </div>
</nav> {% endcomment %}
<div class="container" style="display: flex;">
<div class="welcome-section mt-4">
<p>Welcome, to <span class="highlight"> Balanced_Me </span><br> Women need balance between work and life</p>


<h3>This platform will help women organize their work based on importance and urgency. Moreover, there will be checklist to remind women of taking care of themselves.</h3>
</div>
<img src="//s3.amazonaws.com/appforest_uf/f1631371091485x803765422794940000/Screen%20Shot%202021-09-11%20at%2010.37.40%20AM.png" style="width: 23rem;
margin: 2rem;" alt="">
</div>
<div class="inspiration" >
  <h1>Inspirational Stories</h1>
  <div class="inp" style="display: flex;">
    <div class="con1">
      <h2>Ada Lovelace</h1>
      <h3>The Founder of Scientific Computing and The First Computer Programmer
      </h3>
      <p>First known as the daughter of famed poet Lord Byron, she made her own name by becoming the founder of scientific computing and the first computer programmer. Her algorithm—which history has come to know as the first one designed for a machine to carry out—was intended to be used for Charles Babbage’s Analytical Engine, but Lovelace passed away before the machine was completed. Since her death in 1852, Lovelace’s previously little-known work and approach to science that experts have called "poetical" has broken through to inspire present-day young women interested in computer programming. 

      </p>
    </div>
    <div class="con1">
      <h2>Elizabeth Blackwell</h1>
      <h3>The First Woman Receives A Medical Degree in The United States
      </h3>
      <p>Inspired by the case of her terminally ill friend who wished for a female physician to tend to her, Blackwell made history as the first woman to receive a medical degree in the United States, and the first woman on the Medical Register of the General Medical Council. Born in England but raised in America, Blackwell pushed for social awareness and moral reforms in both countries as she pioneered promoting education for women in medicine. After graduating from medical school, she opened her own practice, and soon opened an infirmary for women and children. She went on to establish the U.S. Sanitary Commission of 1861 under President Lincoln, to encourage sanitary conditions and health in war, and started a medical school for women in the late 1860s. She died in 1910 at 89.

      </p>
    </div>
    <div class="con1">
      <h2>Grace Hopper</h1>
      <h3>Queen of Code
      </h3>
      <p>Best known as the “Queen of Code,” Rear Admiral Hopper was at the forefront of computer and programming language development from her start in the 1930s until she retired from the Navy in 1986—as the oldest serving officer at the time. During World War II, she helped build “Mark I,” one of the world’s earliest computers. After the war, she led the development of computer languages written in English, rather than mathematical notation. Her most known achievement was COBOL, the common business computing language which is still in use today.


      </p>
    </div>

  </div>
</div>
<div class="motivational" style="display: flex; align-items:center; justify-content:center;">
  <img src="//s3.amazonaws.com/appforest_uf/f1631381443504x594027899064591400/Screen%20Shot%202021-09-11%20at%201.30.30%20PM.png" style="width: 55rem;" alt="">
</div>
</div>
{% endblock %}

templates/Home/personal.html
{% extends 'Base.html' %}


{% load static %}
{% block title %} Personal Life {% endblock title %}

{% block body_block %}

<h2 style="margin: 2rem;
font-size: 3rem;
color: #7f23c0;">Let's review your day with your checklist</h2>

<div class="mainboxpersonal" style="display: flex;">
    
    <img src="//s3.amazonaws.com/appforest_uf/f1631372743340x524847865852574800/Screen%20Shot%202021-09-11%20at%2011.03.19%20AM.png" alt="">
    <img src="//s3.amazonaws.com/appforest_uf/f1631372760012x280439989053148830/Screen%20Shot%202021-09-11%20at%2011.03.50%20AM.png" alt="">
    <img src="//s3.amazonaws.com/appforest_uf/f1631372447001x520240970819565900/Screen%20Shot%202021-09-11%20at%2011.00.36%20AM.png" alt="">
</div>
<div class="checkbox" style="display: flex;


    background-color: #e4be98;
    padding: 1rem 1rem;
    box-shadow: 0 20px 20px rgb(0 0 0 / 20%), 0px 0px 50px rgb(0 0 0 / 20%);
    border-radius: 10px;
    flex-wrap:wrap;

 " >
    <div class="relax" style="    display: flex;
    flex-direction: column;
    margin: 1rem;
    width: 31%;
">
        <h1 style="    font-size: 2rem;
        background: #a72c83;
        color: white;
        width: 55%;
        padding: 0 10px;
        border-radius: 11px;
        text-transform: uppercase;">Meditation</h1>
        <input type="checkbox">Did you have a chance to relax today?
        <input type="checkbox">Share your day with beloved ones!
        <input type="checkbox">Enjoy your time with your family!
        <input type="checkbox">Did you enjoy any of your hobbies today?
        <input type="checkbox">Stay on bed and relax!
    
    </div>
    <div class="relax" style="display: flex; flex-direction: column;
     margin: 1rem;
    width: 31%;
    "> <h1 style="    font-size: 2rem;
        background: #a72c83;
        color: white;
        width: 40%;
        padding: 0 10px;
        border-radius: 11px;
        text-transform: uppercase;">Plans</h1>
        <input type="checkbox">Did you have a chance to relax today?
        <input type="checkbox">Share your day with beloved ones!
        <input type="checkbox">Enjoy your time with your family!
        <input type="checkbox">Did you enjoy any of your hobbies today?
        <input type="checkbox">Stay on bed and relax!
    
    </div>
    <div class="relax" style="display: flex; flex-direction: column;
     margin: 1rem;
    width: 31%;">
        <h1 style="    font-size: 2rem;
        background: #a72c83;
        color: white;
        width: 40%;
        padding: 0 10px;
        border-radius: 11px;
        text-transform: uppercase;">Relax</h1>
        <input type="checkbox">Did you have a chance to relax today?
        <input type="checkbox">Share your day with beloved ones!
        <input type="checkbox">Enjoy your time with your family!
        <input type="checkbox">Did you enjoy any of your hobbies today?
        <input type="checkbox">Stay on bed and relax!
    
    </div>
    <div class="relax" style="display: flex; flex-direction: column;
     margin: 1rem;
    width: 31%;">
        <h1 style="    font-size: 2rem;
        background: #a72c83;
        color: white;
        width: 40%;
        padding: 0 10px;
        border-radius: 11px;
        text-transform: uppercase;">skincare</h1>
        <input type="checkbox">Did you have a chance to relax today?
        <input type="checkbox">Share your day with beloved ones!
        <input type="checkbox">Enjoy your time with your family!
        <input type="checkbox">Did you enjoy any of your hobbies today?
        <input type="checkbox">Stay on bed and relax!
    
    </div>
    <div class="relax" style="display: flex; flex-direction: column;
     margin: 1rem;
    width: 31%;">
        <h1 style="    font-size: 2rem;
        background: #a72c83;
        color: white;
        width: 40%;
        padding: 0 10px;
        border-radius: 11px;
        text-transform: uppercase;">workout</h1>
        <input type="checkbox">Did you have a chance to relax today?
        <input type="checkbox">Share your day with beloved ones!
        <input type="checkbox">Enjoy your time with your family!
        <input type="checkbox">Did you enjoy any of your hobbies today?
        <input type="checkbox">Stay on bed and relax!
    
    </div>
    <div class="relax" style="display: flex; flex-direction: column;
     margin: 1rem;
    width: 31%;">
        <h1 style="    font-size: 2rem;
        background: #a72c83;
        color: white;
        width: 40%;
        padding: 0 10px;
        border-radius: 11px;
        text-transform: uppercase;">Diet</h1>
        <input type="checkbox" >Did you have a chance to relax today?
        <input type="checkbox">Share your day with beloved ones!
        <input type="checkbox">Enjoy your time with your family!
        <input type="checkbox">Did you enjoy any of your hobbies today?
        <input type="checkbox">Stay on bed and relax!
    
    </div>
   
</div>

{% endblock body_block %}

templates/Home/productivity.html
{% extends 'Base.html' %}


{% load static %}
{% block title %} Personal Life {% endblock title %}

{% block body_block %}

<h2  style="margin: 2rem;
font-size: 3rem;
color: #7f23c0;">Be the most efficient woman in the world...</h2>
<div class="all" style="display: flex; justify-content: center;
align-items: center;">
    <div class="proim">
        <img src="//s3.amazonaws.com/appforest_uf/f1631378740537x120535507421895000/Screen%20Shot%202021-09-11%20at%2012.45.22%20PM.png" style="width: 34rem;" alt="">
       
       
    </div>
    <div class="buttonpro" style=" box-shadow: 0 0 5px 2px rgb(0 0 0 / 50%);
    padding: 2rem;
    border-radius: 12px;
    background:#D09BB5;
    margin-left: 4rem;"
    >
        <button>How do you feel about your PRODUCTIVITY?</button>
       
        <div class="choosepro" style="display: flex; flex-direction: column; ">
            <input type="checkbox">Not at all...
            <input type="checkbox">Slightly...(from 10% to 40%)
            <input type="checkbox">Decent...(from 50% to 60%)
            <input type="checkbox">Pretty much productive...(from 70% to 80%)
            <input type="checkbox">Extremely productive...(from 90% to 100%)
        </div>
    </div>

</div>

{% endblock body_block %}